// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace SaffronML.Model
{
    public class ModelInput
    {
        [ColumnName("clean_text"), LoadColumn(0)]
        public string SentimentText { get; set; }


        [ColumnName("category"), LoadColumn(1)]
        public float Category { get; set; }


    }
}
